Fix inconsistencies and missing wait script (#76)

diff --git a/deploy/kubernetes/scripts/install b/deploy/kubernetes/scripts/install
--- a/deploy/kubernetes/scripts/install
+++ b/deploy/kubernetes/scripts/install
@@ -124,6 +124,8 @@ if [ "$MINIKUBE" = 1 ]; then
     eval $(minikube docker-env)
 fi
 
+(kubectl get nodes &>/dev/null) || (echo '* kubectl cannot contact cluster, is it setup correctly?' && exit 1)
+
 if [ "$CONFIGURE_TLS" = 1 ]; then
     echo '****************************'
     echo '***  Configuring TLS     ***'
